export default function RegisterLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className={` bg-gray-800 h-svh`}>{children}</div>;
}

// THIS APP IS NO LONGER IN USE. IT IS BEING KEPT IN CASE IT IS NEEDED IN THE FUTURE.
// THIS APP IS NO LONGER IN USE. IT IS BEING KEPT IN CASE IT IS NEEDED IN THE FUTURE.
// THIS APP IS NO LONGER IN USE. IT IS BEING KEPT IN CASE IT IS NEEDED IN THE FUTURE.
// THIS APP IS NO LONGER IN USE. IT IS BEING KEPT IN CASE IT IS NEEDED IN THE FUTURE.
// THIS APP IS NO LONGER IN USE. IT IS BEING KEPT IN CASE IT IS NEEDED IN THE FUTURE.
// THIS APP IS NO LONGER IN USE. IT IS BEING KEPT IN CASE IT IS NEEDED IN THE FUTURE.
// THIS APP IS NO LONGER IN USE. IT IS BEING KEPT IN CASE IT IS NEEDED IN THE FUTURE.
// THIS APP IS NO LONGER IN USE. IT IS BEING KEPT IN CASE IT IS NEEDED IN THE FUTURE.
// THIS APP IS NO LONGER IN USE. IT IS BEING KEPT IN CASE IT IS NEEDED IN THE FUTURE.
// THIS APP IS NO LONGER IN USE. IT IS BEING KEPT IN CASE IT IS NEEDED IN THE FUTURE.
// THIS APP IS NO LONGER IN USE. IT IS BEING KEPT IN CASE IT IS NEEDED IN THE FUTURE.
// THIS APP IS NO LONGER IN USE. IT IS BEING KEPT IN CASE IT IS NEEDED IN THE FUTURE.
// THIS APP IS NO LONGER IN USE. IT IS BEING KEPT IN CASE IT IS NEEDED IN THE FUTURE.
// THIS APP IS NO LONGER IN USE. IT IS BEING KEPT IN CASE IT IS NEEDED IN THE FUTURE.
// THIS APP IS NO LONGER IN USE. IT IS BEING KEPT IN CASE IT IS NEEDED IN THE FUTURE.
