export const placeholderProject = {
  id: "placeholder-id",
  title: "Placeholder Project",
  icon: "🚀",
  status: true,
  description:
    "This is a placeholder task description.This is a placeholder task description.This is a placeholder task description. der task description.This is a placeholderder task description.This is a placeholderder task description.This is a placeholder",
  tasks: [
    {
      id: "placeholder-task-id-1",
      title: "Placeholder Task 1",
      description: "This is a placeholder task description.",
      tags: ["placeholder", "task"],
      points: 3,
      status: "Todo",
      userId: "placeholder-user-id",
      user: {
        id: "placeholder-user-id",
        name: "Placeholder User",
        email: "placeholder@example.com",
      },
      projectId: "placeholder-id",
      sprintId: "placeholder-sprint-id",
      milestoneId: null,
      dueDate: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "placeholder-task-id-2",
      title: "Placeholder Task 2",
      description: "This is another placeholder task description.",
      tags: ["placeholder", "task"],
      points: 5,
      status: "In Progress",
      userId: "placeholder-user-id",
      user: {
        id: "placeholder-user-id",
        name: "Placeholder User",
        email: "placeholder@example.com",
      },
      projectId: "placeholder-id",
      sprintId: "placeholder-sprint-id",
      milestoneId: null,
      dueDate: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],
  sprints: [
    {
      id: "placeholder-sprint-id",
      title: "Placeholder Sprint",
      startDate: new Date(),
      endDate: new Date(),
      status: "Active",
      projectId: "placeholder-id",
      tasks: [
        {
          id: "placeholder-task-id-1",
          title: "Placeholder Task 1",
          description: "This is a placeholder task description.",
          tags: ["placeholder", "task"],
          points: 3,
          status: "In Progress",
          userId: "placeholder-user-id",
          user: {
            id: "placeholder-user-id",
            name: "Placeholder User",
            email: "placeholder@example.com",
          },
          projectId: "placeholder-id",
          sprintId: "placeholder-sprint-id",
          milestoneId: null,
          dueDate: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "placeholder-task-id-2",
          title: "Placeholder Task 2",
          description: "This is another placeholder task description.",
          tags: ["placeholder", "task"],
          points: 5,
          status: "Done",
          userId: "placeholder-user-id",
          user: {
            id: "placeholder-user-id",
            name: "Placeholder User",
            email: "placeholder@example.com",
          },
          projectId: "placeholder-id",
          sprintId: "placeholder-sprint-id",
          milestoneId: null,
          dueDate: null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      createdAt: new Date(),
      updatedAt: new Date(),
      userId: "placeholder-user-id",
      user: {
        id: "placeholder-user-id",
        name: "Placeholder User",
        email: "placeholder@example.com",
      },
    },
  ],
  milestones: [],
  userId: "placeholder-user-id",
  user: {
    id: "placeholder-user-id",
    name: "Placeholder User",
    email: "placeholder@example.com",
  },
  createdAt: new Date(),
  updatedAt: new Date(),
};

export default placeholderProject;
